### ISSUE TITLE
画像の遅れ

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/RobotGuidance#17]
BRIX固有の問題かもしれないが，画像の遅れがある．
遅れた画像に対して適切なコマンドを送ったとしても，画像が遅れているために振動的になる．

https://youtu.be/f6aHMxU-slk

**Comment by yasuohayashibara** [comment]
こちらのコミットの対処をしたところディレイがほぼなくなった．
https://github.com/open-rdc/RobotGuidance/commit/03d843c31131785473492f46783a05723bbdda70

動画
https://youtu.be/SZUDzaLA7Cw

**Comment by yasuohayashibara** [comment]
動きが明らかに安定したので効果があると思われる．
解決したのでissueを閉じます．

**Comment by Pethon** [comment]
bagファイルを取るのはパソコンが重くなり、画像が遅れる原因です。

00:00-00:08 bagファイルを取っている状態の動画、
00:08-00:14 bagファイルを取らない状態の動画です。
動画
[https://youtu.be/cgI3LFJi6ng](url)

**Comment by yasuohayashibara** [comment]
@Pethon 動画が何を示しているのかが分かりませんので，解説をお願いします．

**Comment by Pethon** [comment]
@yasuohayashibara 編集しました。
