### ISSUE TITLE
実験結果の解析

### ISSUE THREAD

**Issue by Pethon** [open-rdc/RobotGuidance#19]
2017/09/21
報酬の移動平均のグラフ（区間１０００）
![reward](https://user-images.githubusercontent.com/19383917/30725925-f692429c-9f82-11e7-8c94-4a1972d00d5a.png)

2200回目から報酬が下がり始めたことを確認できました。
報酬の遅れ問題も確認したが、問題なく正常に0.2秒の周期でした。

報酬の平均周期　0.200369782
報酬の最長周期　0.203059968

**Comment by Pethon** [comment]
2017/09/22
実験を行った最中に、パソコンの電源が落ちてしまったため、
bagファイルをちゃんと保存できず、中身のlogを見られていません。
bagファイルは下のリンクにアップロードしました。
[https://drive.google.com/open?id=0B6WmN6afJ0WJM25OYjdHSG1VcjQ](url)
rosbag reindex と
rosbag fix というコマンドで回復できるそうですが、うまく行けませんでした。

cpuの温度は学習中に熱くないと思います。
電源が落ちる前に、温度が少し上がったが、学習のスピードに影響しないと思います。
cpuのグラフです。
![20170922_cpu_temp](https://user-images.githubusercontent.com/19383917/30756841-3927033e-a007-11e7-8657-cacea453cd4f.png)

**Comment by Pethon** [comment]
2017/09/23
実験結果の動画
[https://youtu.be/w3dGtF3V81o](url)

**Comment by Pethon** [comment]
2017/09/24
報酬の生データと移動平均した値。
[https://drive.google.com/open?id=0B6WmN6afJ0WJd29RRzRfamtfOWc](url)

報酬の移動平均のグラフ（区間２０００）
![2017-09-24_reward](https://user-images.githubusercontent.com/19383917/30781076-95d65c04-a153-11e7-95bf-cb8fcec9a3b2.png)

**Comment by yasuohayashibara** [comment]
SI2017の予稿集を提出して解析が一段落したので，issueを閉じます．
