### ISSUE TITLE
ソース・コードの整理

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/RobotGuidance#20]
だいぶ複雑になってきましたので，以下のブランチでソース・コードの整理を行いました．
https://github.com/open-rdc/RobotGuidance/tree/generalize

アクションの数をlaunchファイルのparamから変更できるようにしました．
GPUが無くてもエラーが発生しないような処理も入れました．
チェックプログラムはrobot_guidance_checkにまとめました．

火曜日以降になると思いますが，一段落したらこちらをmasterにマージしたいと思います．

**Comment by yasuohayashibara** [comment]
@Pethon こちらのソース・コードで実ロボットが動作するかをチェックして下さい．
本日(10/03)時間があったら，記憶が薄れないうちに行なってしまいましょう．

**Comment by Pethon** [comment]
@yasuohayashibara ソースコードはエラーなく、シミュレータで実行できましたが、
間違っているコードがあります（cmd_velの値など）。

**Comment by yasuohayashibara** [comment]
修正お願いします．

**Comment by Pethon** [comment]
分かりました。
できましたら、またコメントします。

**Comment by Pethon** [comment]
mergeしました。

**Comment by yasuohayashibara** [comment]
解決したのでissueを閉じます．
