### ISSUE TITLE
cv_bridgeにより、core dump

### ISSUE THREAD

**Issue by Pethon** [open-rdc/RobotGuidance#22]
`self.cv_image = self.bridge.imgmsg_to_cv2(data, "bgr8")`
というコードを実行するときに、たまにSegmentation Fault (core dump)というエラーが出て、プログラムが止まる。

似てるような問題
[https://answers.ros.org/question/136351/memory-leak-in-imgmsg_to_cv2/](https://answers.ros.org/question/136351/memory-leak-in-imgmsg_to_cv2/)
[https://stackoverflow.com/questions/33971444/segmentation-fault-core-dumped-when-using-cv-bridgeros-indigo-and-opencv-3](https://stackoverflow.com/questions/33971444/segmentation-fault-core-dumped-when-using-cv-bridgeros-indigo-and-opencv-3)
[https://answers.ros.org/question/240467/cv_bridge-ros-image-segmentation-fault-core-dumped/](https://answers.ros.org/question/240467/cv_bridge-ros-image-segmentation-fault-core-dumped/)
[https://github.com/ros-perception/vision_opencv/issues/190](https://github.com/ros-perception/vision_opencv/issues/190)
[https://blog.csdn.net/xyz599/article/details/71970689](https://blog.csdn.net/xyz599/article/details/71970689)

**Comment by Pethon** [comment]
現在カメラから30Hzで生データの画像を取得しているので、周期が高いから処理が間に合わないかと考えられる。
そのため、10Hzに変更してみることを検討している。

**Comment by Pethon** [comment]
@yasuohayashibara このissueで解決方法を検討します。

**Comment by Pethon** [comment]
launchファイルのパラメーターを変えてもカメラの周期が変わらないため，しばらくuvc_cameraの代わりに，OpenCVを利用します．

**Comment by yasuohayashibara** [comment]
解決していると思われるので，issueを閉じます．
