### ISSUE TITLE
前進の行動を選択しない問題

### ISSUE THREAD

**Issue by Pethon** [open-rdc/RobotGuidance#24]
実ロボットを用いて実験を行うと，ロボットが前進しないことが多い．
ロボットがより高い報酬がもらえる行動を探索しきれない理由は，正の報酬を与えているからだと考えられる．
シミュレーター上で，正の報酬は，ロボットが前進の行動を選択しないことに関係あるかを確認する．

実験方法
ロボットの行動：前進，右旋回，左旋回，停止
報酬：正の値，負の値
最高の報酬：正の報酬は2.0，負の報酬は0.0
学習回数：1万ステップまで
緑の円が人間とする

ロボットが旋回すると，緑の円が左右に動く．
ロボットが前進すると，緑の円のサイズが大きくなる．
高い報酬を習得できる条件は，緑の円が真ん中にあって，ちょうどいいサイズになる状態という条件
環境が100回ごとにリセットする（緑の円をランダムなサイズと場所に配置する）

シミュレーターのソースコードは
[https://github.com/open-rdc/RobotGuidance/tree/master/ros/robot_guidance/robot_guidance_check](https://github.com/open-rdc/RobotGuidance/tree/master/ros/robot_guidance/robot_guidance_check)

実行コマンド
`roslaunch robot_guidance_check robot_guidance_check_all.launch`

実験動画
[https://youtu.be/lqNL80b51PA](https://youtu.be/lqNL80b51PA)

実験結果
各報酬実験回数：10回
正の報酬
　　前進の行動を選択する回数：4回
　　前進の行動を選択しない回数：6回
負の報酬
　　前進の行動を選択する回数：10回
　　前進の行動を選択しない回数：0回

以下のグラフ
青い線：負の報酬を利用した場合
赤い線：正の報酬を利用した場合
（この２つの報酬を比較できるように，負の平均報酬をとってから２で足して，両方とも最高報酬が2.0になる）

実験１
![screenshot from 2018-08-23 14 42 51](https://user-images.githubusercontent.com/19383917/44508777-8f356780-a6ea-11e8-8fff-7bdd0330c3ae.png)

実験2
![screenshot from 2018-08-23 14 47 01](https://user-images.githubusercontent.com/19383917/44508787-9492b200-a6ea-11e8-9102-cee705140be3.png)

実験3
![screenshot from 2018-08-23 14 48 56](https://user-images.githubusercontent.com/19383917/44508796-978da280-a6ea-11e8-9f0f-7c8a9ff28b1b.png)

実験4
![screenshot from 2018-08-23 14 50 16](https://user-images.githubusercontent.com/19383917/44508806-9b212980-a6ea-11e8-8e4a-578d0ed72c6d.png)

実験5
![screenshot from 2018-08-23 14 51 57](https://user-images.githubusercontent.com/19383917/44508808-9eb4b080-a6ea-11e8-836e-85c9d7205638.png)

実験6
![screenshot from 2018-08-23 15 16 48](https://user-images.githubusercontent.com/19383917/44508812-a1afa100-a6ea-11e8-9942-1e5c2a9be3c9.png)

実験7
![screenshot from 2018-08-23 15 17 53](https://user-images.githubusercontent.com/19383917/44508815-a411fb00-a6ea-11e8-862a-8532a8e85a16.png)

実験8
![screenshot from 2018-08-23 15 19 19](https://user-images.githubusercontent.com/19383917/44508823-a6745500-a6ea-11e8-998d-9db8d7c8cbcb.png)

実験9
![screenshot from 2018-08-23 15 23 34](https://user-images.githubusercontent.com/19383917/44508826-a96f4580-a6ea-11e8-99a0-c67c783e2a62.png)

実験10
![screenshot from 2018-08-23 15 35 02](https://user-images.githubusercontent.com/19383917/44508829-ac6a3600-a6ea-11e8-9553-5d3362c0564a.png)

**Comment by yasuohayashibara** [comment]
動画のリンクが切れています．

**Comment by Pethon** [comment]
@yasuohayashibara 6000回までの報酬です。（充電しないといけないので、一旦休憩です）
![screenshot from 2018-08-23 19 36 53](https://user-images.githubusercontent.com/19383917/44520897-48f10000-a70c-11e8-8a27-699a41a95b48.png)

**Comment by yasuohayashibara** [comment]
シミュレーションのように一様に上昇していくというわけではなさそうですね．

**Comment by Pethon** [comment]
シミュレーターより複雑なので、収束はこれからかもしれません。

**Comment by Pethon** [comment]
@yasuohayashibara 
6800ステップだけ学習したが，学習中には結構追従できたので，試しで本番の追従をさせてみました．
![screenshot from 2018-08-23 22 08 19](https://user-images.githubusercontent.com/19383917/44527249-44831200-a721-11e8-86fd-a1131f74713d.png)

9:30からが追従フェーズです．
普通の速度で再生します．
ロボットとの距離がだいたい30-50cmだと思います．（１マス目〜1.5マス目）
[https://youtu.be/NZRAIXqeHEg](https://youtu.be/NZRAIXqeHEg)

**Comment by yasuohayashibara** [comment]
動画を見る限り追従及び停止ができているように思います．
本日，申し込みに関する議論ができればと思います．

**Comment by Pethon** [comment]
負の報酬を与えるとロボットがちゃんと探索してくれるので，前進しない問題を解けました．
