### ISSUE TITLE
エピソードの切り替える条件

### ISSUE THREAD

**Issue by Pethon** [open-rdc/RobotGuidance#25]
ロボットが間違った方向に旋回して，人を映らなくなった場合には，そのエピソードを終了して新しいエピソードを始めるべきなのか，回復できるまで待つべきなのかを議論する．

**Comment by yasuohayashibara** [comment]
先ほど直接議論しましたが，STEP数で定期的に切り替えた方が良いと思います．

**Comment by Pethon** [comment]
シミュレーター上では，決めたstep数になるまで待つが， #26 の範囲制限をつけて実験します．
実ロボットの場合は，人を映られなくなったら，すぐにエピソードを切り替えて映られるように移動する．
