### ISSUE TITLE
範囲制限について

### ISSUE THREAD

**Issue by Pethon** [open-rdc/RobotGuidance#26]
同じパラメータ（重み，バイアスなど）で範囲制限ありとなしで実験しました．

実験結果
![screenshot from 2018-08-24 17 52 39](https://user-images.githubusercontent.com/19383917/44575657-6afb8880-a7c7-11e8-9903-27c234ffa141.png)

拡大すると，
![screenshot from 2018-08-24 17 55 07](https://user-images.githubusercontent.com/19383917/44575678-7a7ad180-a7c7-11e8-890d-87b37c7b2d9a.png)

実験動画
範囲制限なし　[https://youtu.be/zov30t2qOCQ](https://youtu.be/zov30t2qOCQ)
範囲制限あり　[https://youtu.be/2kY10B_px3M](https://youtu.be/2kY10B_px3M)

**Comment by yasuohayashibara** [comment]
先ほど直接話しましたが，条件が同じであればどちらを採用しても構わないと思います．
あくまでチェック用のプログラムですので，傾向が分かれば良い程度だと考えています．

**Comment by Pethon** [comment]
無駄の学習がないように，範囲制限をつけて実験します．
