### ISSUE TITLE
エピソードを切替の効果

### ISSUE THREAD

**Issue by Pethon** [open-rdc/RobotGuidance#27]
実験結果

実験1
![screenshot from 2018-08-26 05 20 46](https://user-images.githubusercontent.com/19383917/44624880-a7e58d80-a935-11e8-9e4b-b9672f71e742.png)

実験2
![screenshot from 2018-08-26 05 21 53](https://user-images.githubusercontent.com/19383917/44624881-ad42d800-a935-11e8-998f-e656eca4a270.png)

実験3
![screenshot from 2018-08-26 05 23 08](https://user-images.githubusercontent.com/19383917/44624882-af0c9b80-a935-11e8-9c83-81dce4d5b29d.png)

実験4
![screenshot from 2018-08-26 05 24 19](https://user-images.githubusercontent.com/19383917/44624883-b03dc880-a935-11e8-8efc-a4edb88d5a47.png)

実験5
![screenshot from 2018-08-26 05 25 42](https://user-images.githubusercontent.com/19383917/44624884-b2078c00-a935-11e8-931d-c41ff543cfb8.png)

実験6
![screenshot from 2018-08-26 05 26 39](https://user-images.githubusercontent.com/19383917/44624885-b3d14f80-a935-11e8-91e6-7f94ea20b596.png)

実験7
![screenshot from 2018-08-26 05 27 49](https://user-images.githubusercontent.com/19383917/44624886-b5027c80-a935-11e8-8da8-b21b75b7d4eb.png)

実験8
![screenshot from 2018-08-26 05 29 27](https://user-images.githubusercontent.com/19383917/44624887-b633a980-a935-11e8-92f0-8250c539a7a2.png)

実験9
![screenshot from 2018-08-26 05 30 12](https://user-images.githubusercontent.com/19383917/44624888-b764d680-a935-11e8-92be-27ef1d87c71e.png)

実験10
![screenshot from 2018-08-26 05 30 58](https://user-images.githubusercontent.com/19383917/44624889-b8960380-a935-11e8-8427-785d0c4a80ba.png)

**Comment by Pethon** [comment]
@yasuohayashibara 実験結果から見ると，エピソード切り替えてもあまり効果がないです．（バッグはもうないと思いますが，念の為にもう一度確認していただきたいです．）
考えられる理由は，今の割引率が0.95ですので，0.95^100は0.006ぐらいです．学習にあまり影響しないと思います．
利用しても，学習は早くならないが，人間の挙動による誤学習を防止できるぐらいだと思います．

**Comment by yasuohayashibara** [comment]
こちらの計算に使用したプログラムのリンクをお願いします．

**Comment by Pethon** [comment]
@yasuohayashibara 
この２つのファイルです．
[https://github.com/open-rdc/RobotGuidance/blob/master/ros/robot_guidance/robot_guidance_check/scripts/dummy_robot_all.py](https://github.com/open-rdc/RobotGuidance/blob/master/ros/robot_guidance/robot_guidance_check/scripts/dummy_robot_all.py)
[https://github.com/open-rdc/RobotGuidance/blob/master/ros/robot_guidance/robot_guidance/scripts/robot_guidance_node.py](https://github.com/open-rdc/RobotGuidance/blob/master/ros/robot_guidance/robot_guidance/scripts/robot_guidance_node.py)

agentはこちらで
[https://github.com/open-rdc/RobotGuidance/tree/master/agent](https://github.com/open-rdc/RobotGuidance/tree/master/agent)

**Comment by yasuohayashibara** [comment]
チェックが遅れており申し訳ありません．
まだ動作確認しただけで何とも言えないので，もう少し検討したいと思います．

**Comment by yasuohayashibara** [comment]
@Pethon  ３つめの引数の意味を知っていたら教えて下さい．
self.action = self.rl.stop_episode_and_train(imgobj, self.reward, self.done)

**Comment by Pethon** [comment]
@yasuohayashibara 
doneはこのエピソードが本当に終わるかどうかを確認するだけだと思います。
[https://chainerrl.readthedocs.io/en/latest/_modules/chainerrl/agents/reinforce.html#REINFORCE](https://chainerrl.readthedocs.io/en/latest/_modules/chainerrl/agents/reinforce.html#REINFORCE)
このサイトによると、done=falseの場合には、このエピソードを無視すると書いてあります。
未完成のエピソードを誤学習しないように確認していると思います。

**Comment by yasuohayashibara** [comment]
あまり効果がないという結論でしたので，issueを閉じます．
必要に応じて再度オープンします．
